#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the $wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later: values already saved to %s are offered as defaults.%s\n' "$ENV_FILE" "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
# die "..." stops the wizard with an error.
die()  { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2; exit 1; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s%s [y/N] ' "$YELLOW" "$1" "$RESET"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _check_key KEY dies unless KEY is a valid shell/.env variable name.
_check_key() {
  [[ "$1" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || die "invalid variable name '$1': use letters, digits and _"
}

# _existing KEY: current value of KEY in ENV_FILE, if any. Undoes write_env's
# double-quote escaping so re-runs round-trip.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value=${line#*=}
  if [[ ${#value} -ge 2 && "$value" == \"*\" ]]; then
    value=$(printf '%s' "${value:1:${#value}-2}" | sed 's/\\\([\\"$`]\)/\1/g')
  elif [[ ${#value} -ge 2 && "$value" == \'*\' ]]; then
    value=${value:1:${#value}-2}
  fi
  printf '%s' "$value"
}

# _ask KEY PROMPT PATTERN HIDDEN is the shared body of ask / ask_secret.
_ask() {
  local key="$1" prompt="$2" pattern="$3" hidden="$4" current input eof
  _check_key "$key"
  current=$(_existing "$key" || true)
  # Only offer a saved value as the default if it still passes the check.
  if [[ -n "$pattern" && -n "$current" && ! "$current" =~ $pattern ]]; then current=""; fi
  while :; do
    if [[ -n "$current" ]]; then
      printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
      printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    eof=0
    if [[ "$hidden" == 1 ]]; then
      read -rs input || eof=1
      printf '\n'
    else
      read -r input || eof=1
    fi
    [[ -z "$input" && -n "$current" ]] && input="$current"
    if [[ -z "$input" ]]; then
      (( eof )) && die "input ended before $key was entered"
      warn "a value is required"
    elif [[ -n "$pattern" && ! "$input" =~ $pattern ]]; then
      (( eof )) && die "input ended before a valid $key was entered"
      warn "that doesn't look right: expected a value matching $pattern"
    else
      break
    fi
  done
  printf -v "$key" '%s' "$input"
}

# ask KEY "Prompt" ['regex'] reads a value into $KEY. Offers the existing .env
# value as a default on re-runs (Enter keeps it). Visible input (non-secret).
# Re-prompts until the value is non-empty and, if a bash regex is given,
# matches it (e.g. '^pk_test_').
ask() { _ask "$1" "$2" "${3:-}" 0; }

# ask_secret KEY "Prompt" ['regex'] is like ask, but input is hidden.
ask_secret() { _ask "$1" "$2" "${3:-}" 1; }

# _check_env_ignored runs once, before the first write: inside a git work tree,
# an ENV_FILE that isn't gitignored could get secrets committed, so warn and
# ask. Outside a git repo it does nothing.
_ENV_IGNORE_CHECKED=0
_check_env_ignored() {
  (( _ENV_IGNORE_CHECKED )) && return 0
  _ENV_IGNORE_CHECKED=1
  local dir base
  dir=$(dirname -- "$ENV_FILE"); base=$(basename -- "$ENV_FILE")
  command -v git >/dev/null 2>&1 || return 0
  git -C "$dir" rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 0
  git -C "$dir" check-ignore -q -- "$base" && return 0
  warn "$ENV_FILE is not gitignored, so secrets written to it could be committed."
  note "Fix: echo '$base' >> .gitignore"
  confirm "Write secrets to an un-ignored $ENV_FILE anyway?" \
    || die "stopped: add $ENV_FILE to .gitignore, then re-run"
}

# write_env KEY VALUE upserts KEY="VALUE" into ENV_FILE (creates it with mode
# 600; replaces any existing line). The value is double-quoted with \ " $ and
# backtick escaped, so spaces, # and quotes survive dotenv parsers. Idempotent.
write_env() {
  local key="$1" value="$2" tmp mode
  _check_key "$key"
  if [[ "$value" == *$'\n'* ]]; then
    warn "not writing $key: the value contains a newline"
    SKIPPED+=("$key in $ENV_FILE (value contained a newline)")
    return 0
  fi
  _check_env_ignored
  # Temp file beside ENV_FILE so mv is an atomic same-filesystem rename;
  # mktemp creates it mode 600.
  tmp=$(mktemp "${ENV_FILE}.XXXXXX")
  if [[ -f "$ENV_FILE" ]]; then
    grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || [[ $? -eq 1 ]] \
      || { rm -f "$tmp"; die "couldn't read $ENV_FILE"; }
    # Keep an existing file's mode (GNU stat, then BSD stat).
    if mode=$(stat -c %a "$ENV_FILE" 2>/dev/null || stat -f %Lp "$ENV_FILE" 2>/dev/null); then
      chmod "$mode" "$tmp"
    fi
  fi
  printf '%s="%s"\n' "$key" "$(printf '%s' "$value" | sed 's/[\\"$`]/\\&/g')" >> "$tmp"
  mv -f "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# _gh_ready succeeds if gh is installed and logged in; otherwise prints why.
_gh_ready() {
  command -v gh >/dev/null 2>&1 || { printf 'gh is not installed'; return 1; }
  gh auth status >/dev/null 2>&1 || { printf 'gh is not logged in (run: gh auth login)'; return 1; }
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. On failure it
# warns with gh's first error line (never the value) and records it.
set_secret() {
  local name="$1" value="$2" err
  if err=$(_gh_ready) && err=$(printf '%s' "$value" | gh secret set "$name" 2>&1 >/dev/null); then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
    return
  fi
  [[ -n "$value" ]] && err=${err//"$value"/[redacted]}
  err=${err%%$'\n'*}; err=${err:-gh failed}
  SKIPPED+=("GitHub secret $name: $err (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: $err"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2" err
  if err=$(_gh_ready) && err=$(gh variable set "$name" --body "$value" 2>&1 >/dev/null); then
    printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
    return
  fi
  err=${err%%$'\n'*}; err=${err:-gh failed}
  SKIPPED+=("GitHub variable $name: $err (set it manually: gh variable set $name)")
  warn "skipped GitHub variable $name: $err"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=1

banner "Stripe setup"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Stripe: API keys"
say "We'll grab your Stripe test keys and store them for local dev + CI."
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the API keys page, copy the Publishable key (starts pk_test_)."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable key:" '^pk_test_'
step "Click 'Reveal test key' on the Secret key row, then copy it."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
set_secret STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"   # CI needs this one
# ──────────────────────────────────────────────────────────────────────────

finish
