#!/usr/bin/env node
// Mechanical generation from canonical payloads; no user-target installation.
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
function files(dir) {
  return fs.existsSync(dir) ? fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{
    if(e.name==='__pycache__'||e.name.endsWith('.pyc')) return [];
    const p=path.join(dir,e.name);
    if(e.isSymbolicLink()) throw Error(`symlink payload ${p}`);
    return e.isDirectory()?files(p):[p];
  }):[];
}
const scaffold=path.join(root,'assets/scaffold');
const global=path.join(root,'assets/global');
// Move the destination's useful Codex additions into the canonical global core.
for(const rel of ['.agents/skills/minion','.codex/agents']) {
  const source=path.join(scaffold,rel);
  for(const p of files(source)) {
    const dest=path.join(global,rel,path.relative(source,p));
    if(!fs.existsSync(dest)) {fs.mkdirSync(path.dirname(dest),{recursive:true}); fs.copyFileSync(p,dest);}
  }
}
// These exact old payload copies are now supplied by --local-core or global core.
for(const dir of ['.agents/skills','.codex/agents']) {
  for(const p of files(path.join(scaffold,dir))) fs.unlinkSync(p);
}
for(const dir of ['.agents/skills','.codex/agents','.agents/bootstrap/instructions']) {
  for(const p of files(path.join(global,dir))) {
    const dest=path.join(root,dir,path.relative(path.join(global,dir),p));
    fs.mkdirSync(path.dirname(dest),{recursive:true}); fs.copyFileSync(p,dest);
  }
}
function manifest(base,out,filter=()=>true,transient=false) {
  const entries=files(base).map(p=>path.relative(base,p)).filter(p=>filter(p)&&!p.endsWith('manifest.txt')).sort();
  const rows=entries.map(p=>`file\t${p}\tcopy\tManaged Codex asset.`);
  if(transient) rows.unshift('transient_dir\t.codex/state/tmp\tensure_ignored\tIgnored runtime state.');
  fs.writeFileSync(out,'# Generated by tools/sync-assets.mjs; fail-closed TSV contract.\n'+rows.join('\n')+'\n');
}
manifest(scaffold,path.join(scaffold,'manifest.txt'),p=>p!=='.codex/config.toml',true);
manifest(global,path.join(global,'manifest.txt'),p=>!['skills-manifest.txt','agents-manifest.txt'].includes(p));
manifest(path.join(global,'.agents'),path.join(global,'skills-manifest.txt'));
manifest(path.join(global,'.codex'),path.join(global,'agents-manifest.txt'));
for(const pack of ['falcon','herald','web-design']) manifest(path.join(root,'assets/packs',pack,'scaffold'),path.join(root,'assets/packs',pack,'manifest.txt'));
console.log('Canonical core mirrors and manifests synchronized.');
